# Generated by Django 4.2 on 2024-04-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_category_slug_remove_collection_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subscribable',
            field=models.BooleanField(default=False, verbose_name='Subscribable'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('SIMPLE_PRODUCT', 'Simple Product'), ('GROUPED_PRODUCT', 'Grouped Product'), ('EXTERNAL_PRODUCT', 'External/Affiliate Product'), ('VARIABLE_PRODUCT', 'Variable Product'), ('SIMPLE_SUBSCRIPTION', 'Simple Subscription'), ('VARIABLE_SUBSCRIPTION', 'Variable Subscription'), ('PRODUCT_BUNDLE', 'Product Bundle')], default='SIMPLE_PRODUCT', max_length=25),
        ),
    ]
