# Generated by Django 4.2 on 2024-05-09 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_getway',
            new_name='payment_getway_id',
        ),
    ]
