# Generated by Django 4.2 on 2024-05-09 08:27

from django.db import migrations, models
import nxtbn.payment.models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_getway',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_getway_id',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[nxtbn.payment.models.validate_payment_getway]),
        ),
    ]
