# Generated by Django 4.2 on 2024-04-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='getway_response_raw',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
